import { Channel } from "../types";

export const GLOBAL_PLAYLISTS = [
  // ── Core categories from iptv-org (all free public broadcast channels) ──
  "https://iptv-org.github.io/iptv/categories/news.m3u",
  "https://iptv-org.github.io/iptv/categories/sports.m3u",
  "https://iptv-org.github.io/iptv/categories/documentary.m3u",
  "https://iptv-org.github.io/iptv/categories/movies.m3u",
  "https://iptv-org.github.io/iptv/categories/entertainment.m3u",
  "https://iptv-org.github.io/iptv/categories/kids.m3u",
  "https://iptv-org.github.io/iptv/categories/music.m3u",
  "https://iptv-org.github.io/iptv/categories/series.m3u",
  "https://iptv-org.github.io/iptv/categories/science.m3u",
  "https://iptv-org.github.io/iptv/categories/travel.m3u",
  "https://iptv-org.github.io/iptv/categories/nature.m3u",
  "https://iptv-org.github.io/iptv/categories/cooking.m3u",
  "https://iptv-org.github.io/iptv/categories/culture.m3u",
  "https://iptv-org.github.io/iptv/categories/education.m3u",
  "https://iptv-org.github.io/iptv/categories/business.m3u",
  "https://iptv-org.github.io/iptv/categories/animation.m3u",
  "https://iptv-org.github.io/iptv/categories/family.m3u",
  // ── Popular global country feeds (major sources of free broadcast TV) ──
  "https://iptv-org.github.io/iptv/countries/us.m3u",
  "https://iptv-org.github.io/iptv/countries/gb.m3u",
  "https://iptv-org.github.io/iptv/countries/in.m3u",
  "https://iptv-org.github.io/iptv/countries/au.m3u",
  "https://iptv-org.github.io/iptv/countries/ca.m3u",
  "https://iptv-org.github.io/iptv/countries/fr.m3u",
  "https://iptv-org.github.io/iptv/countries/de.m3u",
  "https://iptv-org.github.io/iptv/countries/it.m3u",
  "https://iptv-org.github.io/iptv/countries/es.m3u",
  "https://iptv-org.github.io/iptv/countries/jp.m3u",
  "https://iptv-org.github.io/iptv/countries/br.m3u",
  "https://iptv-org.github.io/iptv/countries/za.m3u",
  "https://iptv-org.github.io/iptv/countries/ae.m3u",
  "https://iptv-org.github.io/iptv/countries/tr.m3u",
  "https://iptv-org.github.io/iptv/countries/pk.m3u",
  "https://iptv-org.github.io/iptv/countries/nl.m3u",
  "https://iptv-org.github.io/iptv/countries/pl.m3u",
  "https://iptv-org.github.io/iptv/countries/ua.m3u",
  // ── Key language feeds ──
  "https://iptv-org.github.io/iptv/languages/eng.m3u",
  "https://iptv-org.github.io/iptv/languages/ara.m3u",
  "https://iptv-org.github.io/iptv/languages/spa.m3u",
  "https://iptv-org.github.io/iptv/languages/fra.m3u",
  "https://iptv-org.github.io/iptv/languages/por.m3u",
  "https://iptv-org.github.io/iptv/languages/hin.m3u",
];

export const FALLBACK_CHANNELS: Channel[] = [
  {
    id: "verified-dw",
    name: "DW English",
    url: "https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Deutsche_Welle_symbol_2012.svg/1200px-Deutsche_Welle_symbol_2012.svg.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: DW English",
  },
  {
    id: "verified-redbull",
    name: "CBS News",
    url: "https://cbsn-us.cbsnstream.cbsnews.com/out/v1/55a8648e8f134e82a470f83d562deeca/master.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/1/10/CBS_News_2020_logo.svg/1200px-CBS_News_2020_logo.svg.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: CBS News",
  },
  {
    id: "verified-cgtn",
    name: "Sky News",
    url: "https://skynewsau-live.akamaized.net/hls/live/2002689/skynewsau-extra1/master.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/en/thumb/e/ef/Sky_News_Australia_logo_%282017%29.svg/1200px-Sky_News_Australia_logo_%282017%29.svg.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: Sky News",
  },
  {
    id: "verified-bbb",
    name: "Big Buck Bunny (Test)",
    url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Big_buck_bunny_poster_big.jpg/800px-Big_buck_bunny_poster_big.jpg",
    group: "Movies",
    gemeinwohlCategory: "Filme & Serien",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Big Buck Bunny (4K Remaster)",
  },
  {
    id: "verified-daserste",
    name: "Caminandes (Test)",
    url: "https://test-streams.mux.dev/test_001/stream.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Caminandes_logo.svg/1200px-Caminandes_logo.svg.png",
    group: "Movies",
    gemeinwohlCategory: "Unterhaltung",
    isRegional: true,
    isUnstable: false,
    currentProgram: "Caminandes 3: Llamigos",
  },
  {
    id: "verified-zdf",
    name: "ZDF HD",
    url: "https://zdf-hls-15.akamaized.net/hls/live/2016498/de/veryhigh/master.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/c/c1/ZDF_logo.svg/1200px-ZDF_logo.svg.png",
    group: "General",
    gemeinwohlCategory: "Unterhaltung",
    isRegional: true,
    isUnstable: false,
    currentProgram: "Live: ZDF",
  },
  {
    id: "verified-ndr",
    name: "NDR Fernsehen HD",
    url: "https://ndrfs-hls.akamaized.net/hls/live/2022885/ndrfs/master.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/9/94/NDR_Fernsehen_2017.svg/1200px-NDR_Fernsehen_2017.svg.png",
    group: "Regional",
    gemeinwohlCategory: "Lokal & Regional",
    isRegional: true,
    isUnstable: false,
    currentProgram: "Live: NDR Nordmagazin",
  },
  {
    id: "verified-tagesschau24",
    name: "tagesschau24 HD",
    url: "https://tagesschau-lh.akamaihd.net/i/tagesschau_1@119231/master.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Tagesschau24_logo_2015.svg/1200px-Tagesschau24_logo_2015.svg.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: true,
    isUnstable: false,
    currentProgram: "Live: Nachrichten",
  },
  // ── Additional Reliable Public Channels ──
  {
    id: "verified-aljazeera",
    name: "Al Jazeera English",
    url: "https://live-hls-web-aje.getaj.net/AJE/index.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/en/thumb/f/f2/Al_Jazeera_English_logo.svg/1200px-Al_Jazeera_English_logo.svg.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: Al Jazeera",
  },
  {
    id: "verified-bloomberg",
    name: "Bloomberg TV",
    url: "https://cdn3.wowza.com/1/ejBGVnFIOW9yRDNj/cGVscHk5/hls/live/playlist.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Bloomberg_logo.svg/1200px-Bloomberg_logo.svg.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: Bloomberg Markets",
  },
  {
    id: "verified-france24-en",
    name: "France 24 English",
    url: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/2/24/France_24_logo.svg/1200px-France_24_logo.svg.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: France 24",
  },
  {
    id: "verified-france24-fr",
    name: "France 24 Français",
    url: "https://static.france24.com/live/F24_FR_HI_HLS/live_web.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/2/24/France_24_logo.svg/1200px-France_24_logo.svg.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: France 24 FR",
  },
  {
    id: "verified-euronews-en",
    name: "Euronews English",
    url: "https://euronewsabcnews-i.akamaihd.net/hls/live/2022950/abcnewshd/index.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Euronews_2022_logo.svg/1200px-Euronews_2022_logo.svg.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: Euronews",
  },
  {
    id: "verified-abc-news",
    name: "ABC News (USA)",
    url: "https://content.uplynk.com/channel/3324f2467c414329b3b0cc5cd987b6be.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/2/20/ABC_News_logo_2022.svg/1200px-ABC_News_logo_2022.svg.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: ABC News USA",
  },
  {
    id: "verified-pbs-kids",
    name: "PBS Kids",
    url: "https://lh.pbskids.org/hls/pbskids-cbn/master.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/4/44/PBS_Kids_logo_2022.svg/1200px-PBS_Kids_logo_2022.svg.png",
    group: "Kids",
    gemeinwohlCategory: "Kinder & Familie",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: PBS Kids",
  },
  {
    id: "verified-kika-hd",
    name: "KiKA HD",
    url: "https://kikageode.akamaized.net/hls/live/2022393/kika/master.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/1/14/KiKA_logo.svg/1200px-KiKA_logo.svg.png",
    group: "Kids",
    gemeinwohlCategory: "Kinder & Familie",
    isRegional: false,
    isUnstable: false,
    currentProgram: "KiKA TV",
  },
  {
    id: "verified-nick-jr",
    name: "Nick Jr. Global",
    url: "https://plutotv.amagi.tv/playlist/nickjr-pluto-es/playlist.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Nick_Jr._2023_logo.svg/1200px-Nick_Jr._2023_logo.svg.png",
    group: "Kids",
    gemeinwohlCategory: "Kinder & Familie",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Nick Jr. Shows",
  },
  {
    id: "verified-lego-channel",
    name: "LEGO Channel",
    url: "https://samsung-lego-de.amagi.tv/playlist.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/2/24/LEGO_logo.svg/1200px-LEGO_logo.svg.png",
    group: "Kids",
    gemeinwohlCategory: "Kinder & Familie",
    isRegional: false,
    isUnstable: false,
    currentProgram: "LEGO Universe",
  },
  {
    id: "verified-redbull-tv",
    name: "Red Bull TV",
    url: "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/1/13/Red_Bull_GmbH_logo.svg/1200px-Red_Bull_GmbH_logo.svg.png",
    group: "Sports",
    gemeinwohlCategory: "Sport & Action",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: Red Bull TV",
  },
  {
    id: "verified-nasa-tv",
    name: "NASA TV",
    url: "https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/1200px-NASA_logo.svg.png",
    group: "Science",
    gemeinwohlCategory: "Doku & Wissen",
    isRegional: false,
    isUnstable: false,
    currentProgram: "NASA Television",
  },
  {
    id: "verified-cgtn",
    name: "CGTN (China Global TV)",
    url: "https://live.cgtn.com/1000/prog_index.m3u8",
    logo: "https://wsrv.nl/?url=upload.wikimedia.org/wikipedia/commons/thumb/c/c1/CGTN_logo.svg/1200px-CGTN_logo.svg.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: CGTN World",
  },
  {
    id: "verified-arirang",
    name: "Arirang TV (Korea)",
    url: "https://live.arirang.com/live/arirang-tv/master.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Arirang_TV_logo.svg/1200px-Arirang_TV_logo.svg.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: Arirang TV",
  },
  {
    id: "verified-rt-en",
    name: "RT Documentary",
    url: "https://rt-doc.rttv.com/live/rtdoc/playlist.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/RT_logo.svg/1200px-RT_logo.svg.png",
    group: "Documentary",
    gemeinwohlCategory: "Doku & Wissen",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: RT Documentary",
  },
  {
    id: "verified-bloomberg-int",
    name: "i24 News (English)",
    url: "https://bcovlive-a.akamaihd.net/e5c2bde0f96046b7886d2a84ab37af41/eu-central-1/5374356693001/profile_0/chunklist.m3u8",
    logo: "https://i.imgur.com/2A8Y2kY.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: i24News",
  },
];

// Curated stock videos for cinematic pre-roll bumps based on genre
export const GENRE_BUMPERS: Record<string, string> = {
  News: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
  Movies:
    "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  Sports:
    "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
  Entertainment:
    "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
  Kids: "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  Music:
    "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
  Default:
    "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
};

export const GEMEINWOHL_CATEGORIES = [
  "Filme & Serien",
  "Sport & Action",
  "Doku & Wissen",
  "Nachrichten & Info",
  "Shows & Comedy",
  "Kinder & Familie",
  "Lokal & Regional",
  "Unterhaltung",
  "Public EarthCams",
];
