import { Channel } from "../types";

export const GLOBAL_PLAYLISTS = [
  "https://iptv-org.github.io/iptv/categories/documentary.m3u",
  "https://iptv-org.github.io/iptv/categories/series.m3u",
];

export const VERIFIED_RELIABLE_CHANNELS: Channel[] = [
  {
    id: "verified-dw",
    name: "DW English",
    url: "https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Deutsche_Welle_logo.svg/1200px-Deutsche_Welle_logo.svg.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: DW News Desk",
  },
  {
    id: "verified-redbull",
    name: "Red Bull TV",
    url: "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f5/Red_Bull_TV_logo.svg/1200px-Red_Bull_TV_logo.svg.png",
    group: "Sports & Action",
    gemeinwohlCategory: "Sport & Action",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: Red Bull Cliff Diving World Series",
  },
  {
    id: "verified-cgtn",
    name: "CGTN Global",
    url: "https://news.cgtn.com/resource/live/english/cgtn-news.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/CGTN_logo.svg/1200px-CGTN_logo.svg.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Live: Global Watch",
  },
  {
    id: "verified-bbb",
    name: "Big Buck Bunny (Test)",
    url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Big_buck_bunny_poster_big.jpg/800px-Big_buck_bunny_poster_big.jpg",
    group: "Movies",
    gemeinwohlCategory: "Filme & Serien",
    isRegional: false,
    isUnstable: false,
    currentProgram: "Big Buck Bunny (4K Remaster)",
  },
  {
    id: "verified-daserste",
    name: "Das Erste (ARD) HD",
    url: "https://mcdn.daserste.de/daserste/de/master.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Das_Erste_2014.svg/1200px-Das_Erste_2014.svg.png",
    group: "General",
    gemeinwohlCategory: "Unterhaltung",
    isRegional: true,
    isUnstable: false,
    currentProgram: "Live: Das Erste",
  },
  {
    id: "verified-zdf",
    name: "ZDF HD",
    url: "https://zdf-hls-15.akamaized.net/hls/live/2016498/de/veryhigh/master.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/ZDF_logo.svg/1200px-ZDF_logo.svg.png",
    group: "General",
    gemeinwohlCategory: "Unterhaltung",
    isRegional: true,
    isUnstable: false,
    currentProgram: "Live: ZDF",
  },
  {
    id: "verified-ndr",
    name: "NDR Fernsehen HD",
    url: "https://ndrfs-hls.akamaized.net/hls/live/2022885/ndrfs/master.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/NDR_Fernsehen_2017.svg/1200px-NDR_Fernsehen_2017.svg.png",
    group: "Regional",
    gemeinwohlCategory: "Lokal & Regional",
    isRegional: true,
    isUnstable: false,
    currentProgram: "Live: NDR Nordmagazin",
  },
  {
    id: "verified-tagesschau24",
    name: "tagesschau24 HD",
    url: "https://tagesschau-lh.akamaihd.net/i/tagesschau_1@119231/master.m3u8",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Tagesschau24_logo_2015.svg/1200px-Tagesschau24_logo_2015.svg.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: true,
    isUnstable: false,
    currentProgram: "Live: Nachrichten",
  },
];

export const GEMEINWOHL_CATEGORIES = [
  "Filme & Serien",
  "Sport & Action",
  "Doku & Wissen",
  "Nachrichten & Info",
  "Shows & Comedy",
  "Kinder & Familie",
  "Lokal & Regional",
  "Unterhaltung",
];
