import { Channel } from "../types";

export const GLOBAL_PLAYLISTS = [
  // ── Core categories from iptv-org (all free public broadcast channels) ──
  "https://iptv-org.github.io/iptv/categories/news.m3u",
  "https://iptv-org.github.io/iptv/categories/sports.m3u",
  "https://iptv-org.github.io/iptv/categories/documentary.m3u",
  "https://iptv-org.github.io/iptv/categories/movies.m3u",
  "https://iptv-org.github.io/iptv/categories/entertainment.m3u",
  "https://iptv-org.github.io/iptv/categories/kids.m3u",
  "https://iptv-org.github.io/iptv/categories/music.m3u",
  "https://iptv-org.github.io/iptv/categories/series.m3u",
  "https://iptv-org.github.io/iptv/categories/science.m3u",
  "https://iptv-org.github.io/iptv/categories/travel.m3u",
  "https://iptv-org.github.io/iptv/categories/nature.m3u",
  "https://iptv-org.github.io/iptv/categories/cooking.m3u",
  "https://iptv-org.github.io/iptv/categories/culture.m3u",
  "https://iptv-org.github.io/iptv/categories/education.m3u",
  "https://iptv-org.github.io/iptv/categories/business.m3u",
  "https://iptv-org.github.io/iptv/categories/animation.m3u",
  "https://iptv-org.github.io/iptv/categories/family.m3u",
  // ── Popular global country feeds (major sources of free broadcast TV) ──
  "https://iptv-org.github.io/iptv/countries/us.m3u",
  "https://iptv-org.github.io/iptv/countries/gb.m3u",
  "https://iptv-org.github.io/iptv/countries/in.m3u",
  "https://iptv-org.github.io/iptv/countries/au.m3u",
  "https://iptv-org.github.io/iptv/countries/ca.m3u",
  "https://iptv-org.github.io/iptv/countries/fr.m3u",
  "https://iptv-org.github.io/iptv/countries/de.m3u",
  "https://iptv-org.github.io/iptv/countries/it.m3u",
  "https://iptv-org.github.io/iptv/countries/es.m3u",
  "https://iptv-org.github.io/iptv/countries/jp.m3u",
  "https://iptv-org.github.io/iptv/countries/br.m3u",
  "https://iptv-org.github.io/iptv/countries/za.m3u",
  "https://iptv-org.github.io/iptv/countries/ae.m3u",
  "https://iptv-org.github.io/iptv/countries/tr.m3u",
  "https://iptv-org.github.io/iptv/countries/pk.m3u",
  "https://iptv-org.github.io/iptv/countries/nl.m3u",
  "https://iptv-org.github.io/iptv/countries/pl.m3u",
  "https://iptv-org.github.io/iptv/countries/ua.m3u",
  // ── Key language feeds ──
  "https://iptv-org.github.io/iptv/languages/eng.m3u",
  "https://iptv-org.github.io/iptv/languages/ara.m3u",
  "https://iptv-org.github.io/iptv/languages/spa.m3u",
  "https://iptv-org.github.io/iptv/languages/fra.m3u",
  "https://iptv-org.github.io/iptv/languages/por.m3u",
  "https://iptv-org.github.io/iptv/languages/hin.m3u",
];

export const FALLBACK_CHANNELS: Channel[] = [
  {
    id: "verified-ndtv",
    name: "NDTV 24x7",
    url: "https://raw.githubusercontent.com/amazeyourself/adaptive-streams/refs/heads/main/streams/in/YuppTV/NDTV24x7.m3u8",
    logo: "https://dtil.tmsimg.com/assets/s154895_ld_h15_aa.png?lock=720x540",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: true,
    region: "India",
    isUnstable: false,
    currentProgram: "Live: NDTV 24x7",
  },
  {
    id: "verified-aajtak",
    name: "Aaj Tak",
    url: "http://103.213.31.109:90/AajtakHD/playlist.m3u8",
    logo: "https://xstreamcp-assets-msp.streamready.in/assets/LIVETV/LIVECHANNEL/LIVETV_LIVETVCHANNEL_AAJ_TAK/images/LOGO_HD/image.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: true,
    region: "India",
    isUnstable: false,
    currentProgram: "Live: Aaj Tak",
  },
  {
    id: "verified-indiatoday",
    name: "India Today",
    url: "https://d1rc86nwwc9fag.cloudfront.net/vglive-sk-293160/master.m3u8",
    logo: "https://xstreamcp-assets-msp.streamready.in/assets/LIVETV/LIVECHANNEL/LIVETV_LIVETVCHANNEL_INDIA_TODAY/images/LOGO_HD/image.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: true,
    region: "India",
    isUnstable: false,
    currentProgram: "Live: India Today",
  },
  {
    id: "verified-zeenews",
    name: "Zee News",
    url: "https://dknttpxmr0dwf.cloudfront.net/index_57.m3u8",
    logo: "https://dtil.tmsimg.com/assets/GNLZZGG0023VWYC.png?lock=720x540",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: true,
    region: "India",
    isUnstable: false,
    currentProgram: "Live: Zee News",
  },
  {
    id: "verified-republic",
    name: "Republic Bangla",
    url: "https://vg-republictvlive.akamaized.net/v1/master/611d79b11b77e2f571934fd80ca1413453772ac7/vglive-sk-456368/main.m3u8",
    logo: "https://xstreamcp-assets-msp.streamready.in/assets/LIVETV/LIVECHANNEL/LIVETV_LIVETVCHANNEL_RSYMDOT_BANGLA/images/LOGO_HD/image.png",
    group: "News",
    gemeinwohlCategory: "Nachrichten & Info",
    isRegional: true,
    region: "India",
    isUnstable: false,
    currentProgram: "Live: Republic TV",
  },
  {
    id: "verified-ddnational",
    name: "DD National",
    url: "http://107.167.16.138/ddnational/index.m3u8?token=test",
    logo: "https://ltsk-cdn.s3.eu-west-1.amazonaws.com/jumpstart/Temp_Live/cdn/HLS/Channel/transparentImages/DD%20National.png",
    group: "Entertainment",
    gemeinwohlCategory: "Unterhaltung",
    isRegional: true,
    region: "India",
    isUnstable: false,
    currentProgram: "Live: DD National",
  }
];

// Curated stock videos for cinematic pre-roll bumps based on genre
export const GENRE_BUMPERS: Record<string, string> = {
  News: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
  Movies:
    "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  Sports:
    "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
  Entertainment:
    "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
  Kids: "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  Music:
    "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
  Default:
    "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
};

export const GEMEINWOHL_CATEGORIES = [
  "Filme & Serien",
  "Sport & Action",
  "Doku & Wissen",
  "Nachrichten & Info",
  "Shows & Comedy",
  "Kinder & Familie",
  "Lokal & Regional",
  "Unterhaltung",
  "Public EarthCams",
];
