import React, { useState, useEffect } from "react";
import {
  BrainCircuit,
  HeartPulse,
  ActivitySquare,
  AlertTriangle,
  ArrowUpRight,
  ArrowDownRight,
  RefreshCw,
  BarChart2,
  Video,
} from "lucide-react";
import { useSmartFeed } from "../../hooks/useSmartFeed";
import { Channel } from "../../types";

import { db } from "../../lib/firebase";
import { doc, onSnapshot, setDoc } from "firebase/firestore";

interface ChannelData {
  id: string;
  name: string;
  group: string;
  url: string;
}

interface AlgorithmConfig {
  healthWeight: number;
  regionalWeight: number;
  categoryWeight: number;
}

interface MetricState {
  totalStreams: number;
  healthyStreams: number;
  deadStreams: number;
  lastScan: string;
  topCategory: string;
  healthScore: number;
}

export const ContentIntelligence: React.FC = () => {
  const [metrics, setMetrics] = useState<MetricState>({
    totalStreams: 0,
    healthyStreams: 0,
    deadStreams: 0,
    lastScan: "Just now",
    topCategory: "Loading...",
    healthScore: 0,
  });

  const [channels, setChannels] = useState<ChannelData[]>([]);
  const [quarantinedStreams, setQuarantinedStreams] = useState<
    { name: string; error: string }[]
  >([]);
  const [simulatedProfile, setSimulatedProfile] = useState("Sports Fan");
  const [simulatedRegion, setSimulatedRegion] = useState("Global");
  const [isScanning, setIsScanning] = useState(false);

  const [config, setConfig] = useState<AlgorithmConfig>({
    healthWeight: 1.0,
    regionalWeight: 1.5,
    categoryWeight: 1.2,
  });

  useEffect(() => {
    const unsub = onSnapshot(doc(db, "algorithm_config", "live"), (snap) => {
      if (snap.exists()) {
        setConfig(snap.data() as AlgorithmConfig);
      }
    });
    return () => unsub();
  }, []);

  const handleConfigChange = async (
    key: keyof AlgorithmConfig,
    value: number,
  ) => {
    const newConfig = { ...config, [key]: value };
    setConfig(newConfig);
    await setDoc(doc(db, "algorithm_config", "live"), newConfig);
  };

  // The actual algorithmic recommendations based on live data
  const { smartFeed } = useSmartFeed(
    channels as unknown as Channel[],
    simulatedProfile,
    simulatedRegion,
  );

  const fetchLiveData = async () => {
    setIsScanning(true);
    try {
      // 1. Fetch live production artifacts generated by GitHub Actions
      const [channelsRes, verifiedRes] = await Promise.all([
        fetch("/channels.json?t=" + Date.now()), // cache bust
        fetch("/verified_streams.json?t=" + Date.now()),
      ]);

      let allChannels: ChannelData[] = [];
      let verified: ChannelData[] = [];

      if (channelsRes.ok) allChannels = await channelsRes.json();
      if (verifiedRes.ok) verified = await verifiedRes.json();

      setChannels(allChannels);

      // 2. Compute dynamic KPI metrics
      const total = allChannels.length;
      const healthy = verified.length;
      const dead = total > healthy ? total - healthy : 0;
      const score = total > 0 ? (healthy / total) * 100 : 0;

      // Group by category to find dominant
      const categoryCounts = verified.reduce(
        (acc, curr) => {
          const group = curr.group || "General";
          acc[group] = (acc[group] || 0) + 1;
          return acc;
        },
        {} as Record<string, number>,
      );

      let topCat = "None";
      let maxCount = 0;
      Object.entries(categoryCounts).forEach(([cat, count]) => {
        if (count > maxCount) {
          maxCount = count;
          topCat = cat;
        }
      });

      setMetrics({
        totalStreams: total,
        healthyStreams: healthy,
        deadStreams: dead,
        lastScan: new Date().toLocaleTimeString(),
        topCategory: topCat,
        healthScore: score,
      });

      // 3. Compute live Quarantined streams (in channels but not in verified)
      const verifiedIds = new Set(verified.map((v) => v.id));
      const deadStreamsList = allChannels
        .filter((c) => !verifiedIds.has(c.id))
        .slice(0, 15) // take top 15 for UI
        .map((c) => ({
          name: c.name || "Unknown Stream",
          error: "Failed Health Check (Auto-Pruned)",
        }));

      setQuarantinedStreams(deadStreamsList);
    } catch (err) {
      console.error("Failed to sync live data:", err);
    } finally {
      setIsScanning(false);
    }
  };

  useEffect(() => {
    fetchLiveData();
  }, []);

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-white flex items-center gap-2">
            <BrainCircuit className="w-6 h-6 text-indigo-500" />
            Content Intelligence
          </h2>
          <p className="text-slate-400 text-sm mt-1">
            Real-time algorithmic insights synced directly with GitHub Actions.
          </p>
        </div>
        <button
          onClick={fetchLiveData}
          disabled={isScanning}
          className={`flex items-center gap-2 px-4 py-2 bg-indigo-600/20 text-indigo-400 hover:bg-indigo-600/30 rounded-lg transition-colors text-sm font-medium border border-indigo-500/20 ${isScanning ? "opacity-50 cursor-not-allowed" : ""}`}
        >
          <RefreshCw
            className={`w-4 h-4 ${isScanning ? "animate-spin" : ""}`}
          />
          {isScanning ? "Syncing..." : "Force Re-Scan"}
        </button>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
            <HeartPulse className="w-16 h-16 text-emerald-500" />
          </div>
          <h3 className="text-slate-400 font-medium text-sm mb-1">
            Network Health Score
          </h3>
          <div className="text-3xl font-black text-white">
            {metrics.healthScore.toFixed(1)}%
          </div>
          <div className="mt-2 text-xs flex items-center text-emerald-400 gap-1">
            <ArrowUpRight className="w-3 h-3" /> Live synced
          </div>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
            <Video className="w-16 h-16 text-blue-500" />
          </div>
          <h3 className="text-slate-400 font-medium text-sm mb-1">
            Healthy Streams
          </h3>
          <div className="text-3xl font-black text-white">
            {metrics.healthyStreams.toLocaleString()}
          </div>
          <div className="mt-2 text-xs flex items-center text-slate-400 gap-1">
            Out of {metrics.totalStreams.toLocaleString()} total
          </div>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
            <AlertTriangle className="w-16 h-16 text-rose-500" />
          </div>
          <h3 className="text-slate-400 font-medium text-sm mb-1">
            Dead / Buffering
          </h3>
          <div className="text-3xl font-black text-white">
            {metrics.deadStreams.toLocaleString()}
          </div>
          <div className="mt-2 text-xs flex items-center text-rose-400 gap-1">
            <ArrowDownRight className="w-3 h-3" /> Auto-demoted in feed
          </div>
        </div>

        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
            <BarChart2 className="w-16 h-16 text-amber-500" />
          </div>
          <h3 className="text-slate-400 font-medium text-sm mb-1">
            Dominant Category
          </h3>
          <div
            className="text-3xl font-black text-white truncate pr-16"
            title={metrics.topCategory}
          >
            {metrics.topCategory}
          </div>
          <div className="mt-2 text-xs flex items-center text-slate-400 gap-1">
            Highest uptime density
          </div>
        </div>
      </div>

      {/* Simulator and Demotions */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Recommendation Simulator */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-8 h-8 rounded-lg bg-indigo-500/20 flex items-center justify-center">
              <ActivitySquare className="w-4 h-4 text-indigo-400" />
            </div>
            <h3 className="text-lg font-semibold text-white">
              Algorithm Simulator
            </h3>
          </div>

          <div className="mb-6">
            <label className="block text-sm font-medium text-slate-400 mb-2">
              Simulate Demographic Profile
            </label>
            <div className="flex gap-2 flex-wrap">
              {["Sports Fan", "News Watcher", "Movie Buff", "General"].map(
                (profile) => (
                  <button
                    key={profile}
                    onClick={() => setSimulatedProfile(profile)}
                    className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${simulatedProfile === profile ? "bg-indigo-600 text-white" : "bg-slate-800 text-slate-400 hover:bg-slate-700"}`}
                  >
                    {profile}
                  </button>
                ),
              )}
            </div>
          </div>

          <div className="mb-6">
            <label className="block text-sm font-medium text-slate-400 mb-2">
              Simulate User Region
            </label>
            <div className="flex gap-2 flex-wrap">
              {["Global", "DE", "US", "Local"].map((region) => (
                <button
                  key={region}
                  onClick={() => setSimulatedRegion(region)}
                  className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${simulatedRegion === region ? "bg-emerald-600 text-white" : "bg-slate-800 text-slate-400 hover:bg-slate-700"}`}
                >
                  {region}
                </button>
              ))}
            </div>
          </div>

          <div className="mb-6 space-y-4 border-t border-slate-800 pt-6">
            <h4 className="text-sm font-medium text-slate-400">
              Live Algorithm Weights (Synced to Frontend)
            </h4>

            <div>
              <div className="flex justify-between text-xs text-slate-400 mb-1">
                <span>Health Weight ({config.healthWeight}x)</span>
              </div>
              <input
                type="range"
                min="0"
                max="3"
                step="0.1"
                value={config.healthWeight}
                onChange={(e) =>
                  handleConfigChange("healthWeight", parseFloat(e.target.value))
                }
                className="w-full accent-indigo-500"
              />
            </div>

            <div>
              <div className="flex justify-between text-xs text-slate-400 mb-1">
                <span>Regional Boost ({config.regionalWeight}x)</span>
              </div>
              <input
                type="range"
                min="1"
                max="5"
                step="0.1"
                value={config.regionalWeight}
                onChange={(e) =>
                  handleConfigChange(
                    "regionalWeight",
                    parseFloat(e.target.value),
                  )
                }
                className="w-full accent-emerald-500"
              />
            </div>

            <div>
              <div className="flex justify-between text-xs text-slate-400 mb-1">
                <span>Category Match ({config.categoryWeight}x)</span>
              </div>
              <input
                type="range"
                min="1"
                max="5"
                step="0.1"
                value={config.categoryWeight}
                onChange={(e) =>
                  handleConfigChange(
                    "categoryWeight",
                    parseFloat(e.target.value),
                  )
                }
                className="w-full accent-amber-500"
              />
            </div>
          </div>

          <div className="space-y-3">
            {smartFeed.slice(0, 3).map((stream: Channel, index: number) => (
              <div
                key={stream.id}
                className="p-4 rounded-xl bg-slate-950/50 border border-slate-800 flex items-center justify-between"
              >
                <div className="truncate pr-4">
                  <h4 className="text-white font-medium truncate">
                    {stream.name}
                  </h4>
                  <p className="text-xs text-slate-400 mt-1">
                    Health:{" "}
                    {stream._intelligence?.healthScore?.toFixed(1) || 99}% •
                    Match: {stream._intelligence?.matchScore || 100}%
                  </p>
                </div>
                <span className="px-2 py-1 bg-emerald-500/20 text-emerald-400 text-xs font-bold rounded whitespace-nowrap">
                  #{index + 1} REC
                </span>
              </div>
            ))}
            {smartFeed.length === 0 && !isScanning && (
              <div className="text-center py-4 text-slate-500 text-sm">
                No recommended streams found.
              </div>
            )}
          </div>
        </div>

        {/* Demoted Streams */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 flex flex-col">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-8 h-8 rounded-lg bg-rose-500/20 flex items-center justify-center">
              <AlertTriangle className="w-4 h-4 text-rose-400" />
            </div>
            <h3 className="text-lg font-semibold text-white">
              Live Quarantined Streams
            </h3>
          </div>
          <p className="text-sm text-slate-400 mb-4">
            These streams failed the real GitHub Action validation check and are
            currently hidden from user feeds.
          </p>

          <div className="space-y-3 flex-1 overflow-y-auto max-h-[300px] pr-2">
            {quarantinedStreams.length > 0 ? (
              quarantinedStreams.map((stream, idx) => (
                <div
                  key={idx}
                  className="p-4 rounded-xl bg-slate-950/50 border border-rose-900/30 flex items-center justify-between"
                >
                  <div className="truncate pr-4">
                    <h4 className="text-white font-medium opacity-70 line-through truncate">
                      {stream.name}
                    </h4>
                    <p className="text-xs text-rose-400 mt-1">
                      Reason: {stream.error}
                    </p>
                  </div>
                  <button className="text-xs font-medium text-slate-500 hover:text-white transition-colors whitespace-nowrap">
                    Inspect
                  </button>
                </div>
              ))
            ) : (
              <div className="text-center py-8 text-emerald-500/70 text-sm flex flex-col items-center">
                <HeartPulse className="w-8 h-8 mb-2 opacity-50" />
                No dead streams detected in last scan!
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
